spring:
  application:
    name: iter
  profiles:
    default: local
  jpa:
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        format_sql: true
    open-in-view: false

jwt:
  issuer: iter
  audience: iter-api
  secret-key: ${JWT_SECRET_KEY}
  access-token-validity: 15m
  refresh-token-validity: 14d

springdoc:
  swagger-ui:
    path: /swagger-ui.html
    operations-sorter: method
  api-docs:
    path: /v3/api-docs

logging:
  level:
    com.example.iter: debug
